version: "3.8"

services:
  postgres:
    image: postgis/postgis:17-master
    container_name: container_postgres_database
    environment:
      POSTGRES_DB: generic
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
    ports:
      - "5433:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
      - postgres_data:/var/lib/postgresql/data
    restart: on-failure
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: server/
      dockerfile: ./Dockerfile
    container_name: container_nest_api
    ports:
      - "4000:4000"
    environment:
      PORT: 4000
      DB_HOST: postgres
      DB_USERNAME: admin
      DB_PASSWORD: admin
      DB_NAME: generic
      DB_PORT: 5432
      SECRET_KEY: notoriun12345678987654321
      ETHEREAL_USER: cedrick77@ethereal.email
      ETHEREAL_PASS: GYRCVANx5jtakuDjK1
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure

  web:
    build:
      context: client/
      dockerfile: ./Dockerfile
    container_name: container_web_client
    ports:
      - "8080:80"
    environment:
      PORT: 8080
      REACT_APP_API_URL: http://localhost:4000
    restart: on-failure

volumes:
  postgres_data:
